// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add_channel(arg1:string,arg2:string,arg3:number,arg4:Array<number>):Promise<void>;

export function ClearBTF():Promise<void>;

export function List_all_stored_files():Promise<Array<string>>;

export function LogFile_to_BTF():Promise<void>;

export function Read_BTF():Promise<void>;

export function Write_BTF(arg1:boolean):Promise<void>;
