// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add_channel(arg1, arg2, arg3, arg4) {
  return window['go']['Backend']['Basic_telemetry_file']['Add_channel'](arg1, arg2, arg3, arg4);
}

export function ClearBTF() {
  return window['go']['Backend']['Basic_telemetry_file']['ClearBTF']();
}

export function List_all_stored_files() {
  return window['go']['Backend']['Basic_telemetry_file']['List_all_stored_files']();
}

export function LogFile_to_BTF() {
  return window['go']['Backend']['Basic_telemetry_file']['LogFile_to_BTF']();
}

export function Read_BTF() {
  return window['go']['Backend']['Basic_telemetry_file']['Read_BTF']();
}

export function Write_BTF(arg1) {
  return window['go']['Backend']['Basic_telemetry_file']['Write_BTF'](arg1);
}
