// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBreakLine(arg1) {
  return window['go']['Backend']['Full_graph']['AddBreakLine'](arg1);
}

export function AddChannelToGraph(arg1, arg2) {
  return window['go']['Backend']['Full_graph']['AddChannelToGraph'](arg1, arg2);
}

export function AddExportMarker(arg1, arg2) {
  return window['go']['Backend']['Full_graph']['AddExportMarker'](arg1, arg2);
}

export function ConfigureGraphsFromLayout(arg1) {
  return window['go']['Backend']['Full_graph']['ConfigureGraphsFromLayout'](arg1);
}

export function ExtractRawDataBetweenTimes(arg1, arg2) {
  return window['go']['Backend']['Full_graph']['ExtractRawDataBetweenTimes'](arg1, arg2);
}

export function GetAvailableChannels() {
  return window['go']['Backend']['Full_graph']['GetAvailableChannels']();
}

export function GetCursorData() {
  return window['go']['Backend']['Full_graph']['GetCursorData']();
}

export function GetExportMarkerPairs() {
  return window['go']['Backend']['Full_graph']['GetExportMarkerPairs']();
}

export function GetGraphMetadata() {
  return window['go']['Backend']['Full_graph']['GetGraphMetadata']();
}

export function GetViewportData(arg1) {
  return window['go']['Backend']['Full_graph']['GetViewportData'](arg1);
}

export function InitializeFromStoredFile() {
  return window['go']['Backend']['Full_graph']['InitializeFromStoredFile']();
}

export function MoveChannelToGraph(arg1, arg2) {
  return window['go']['Backend']['Full_graph']['MoveChannelToGraph'](arg1, arg2);
}

export function RegenerateChannelColor(arg1) {
  return window['go']['Backend']['Full_graph']['RegenerateChannelColor'](arg1);
}

export function RemoveBreakLine(arg1) {
  return window['go']['Backend']['Full_graph']['RemoveBreakLine'](arg1);
}

export function RemoveChannelFromGraph(arg1) {
  return window['go']['Backend']['Full_graph']['RemoveChannelFromGraph'](arg1);
}

export function RemoveExportMarker(arg1, arg2) {
  return window['go']['Backend']['Full_graph']['RemoveExportMarker'](arg1, arg2);
}

export function RemoveGraph(arg1) {
  return window['go']['Backend']['Full_graph']['RemoveGraph'](arg1);
}

export function SetContext(arg1) {
  return window['go']['Backend']['Full_graph']['SetContext'](arg1);
}

export function SetCursorPosition(arg1) {
  return window['go']['Backend']['Full_graph']['SetCursorPosition'](arg1);
}

export function SetGraphSplitAxisMode(arg1, arg2) {
  return window['go']['Backend']['Full_graph']['SetGraphSplitAxisMode'](arg1, arg2);
}

export function SetGraphTitle(arg1, arg2) {
  return window['go']['Backend']['Full_graph']['SetGraphTitle'](arg1, arg2);
}
