// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {Backend} from '../models';
import {context} from '../models';

export function AddBreakLine(arg1:number):Promise<void>;

export function AddChannelToGraph(arg1:string,arg2:number):Promise<void>;

export function AddExportMarker(arg1:number,arg2:boolean):Promise<void>;

export function ConfigureGraphsFromLayout(arg1:Array<Backend.Graph_configuration>):Promise<void>;

export function ExtractRawDataBetweenTimes(arg1:number,arg2:number):Promise<Backend.Data_fragment>;

export function GetAvailableChannels():Promise<Array<Backend.Channel_info>>;

export function GetCursorData():Promise<Record<string, number>>;

export function GetExportMarkerPairs():Promise<Array<any>>;

export function GetGraphMetadata():Promise<Backend.Graph_metadata>;

export function GetViewportData(arg1:Backend.Viewport_request):Promise<Backend.Viewport_response>;

export function InitializeFromStoredFile():Promise<void>;

export function LoadPreviewChannel(arg1:Backend.Telemetry_file,arg2:string):Promise<void>;

export function MoveChannelToGraph(arg1:string,arg2:number):Promise<void>;

export function PreviewValidationChannel(arg1:string):Promise<void>;

export function RegenerateChannelColor(arg1:string):Promise<void>;

export function RemoveBreakLine(arg1:number):Promise<void>;

export function RemoveChannelFromGraph(arg1:string):Promise<void>;

export function RemoveExportMarker(arg1:number,arg2:boolean):Promise<void>;

export function RemoveGraph(arg1:number):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetCursorPosition(arg1:number):Promise<void>;

export function SetGraphSplitAxisMode(arg1:number,arg2:boolean):Promise<void>;

export function SetGraphTitle(arg1:number,arg2:string):Promise<void>;
