// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTag(arg1) {
  return window['go']['Backend']['Telemetry_file']['AddTag'](arg1);
}

export function Baby_serialize() {
  return window['go']['Backend']['Telemetry_file']['Baby_serialize']();
}

export function GetAllChannelNames() {
  return window['go']['Backend']['Telemetry_file']['GetAllChannelNames']();
}

export function GetAllChannelUnvalidatedNames() {
  return window['go']['Backend']['Telemetry_file']['GetAllChannelUnvalidatedNames']();
}

export function GetData(arg1) {
  return window['go']['Backend']['Telemetry_file']['GetData'](arg1);
}

export function Load_telemetry_file(arg1) {
  return window['go']['Backend']['Telemetry_file']['Load_telemetry_file'](arg1);
}

export function RemoveTag(arg1) {
  return window['go']['Backend']['Telemetry_file']['RemoveTag'](arg1);
}

export function SetName(arg1) {
  return window['go']['Backend']['Telemetry_file']['SetName'](arg1);
}

export function ValidateChannel(arg1) {
  return window['go']['Backend']['Telemetry_file']['ValidateChannel'](arg1);
}
