// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {Backend} from '../models';

export function ClearAllFragments():Promise<void>;

export function ConcatenateAllFragments():Promise<string>;

export function DeleteConcatenatedFragment():Promise<void>;

export function DeleteFragment(arg1:string):Promise<void>;

export function ExecuteTool(arg1:string,arg2:string,arg3:Record<string, any>):Promise<Backend.Tool_result>;

export function ExtractDataFragment(arg1:number,arg2:number):Promise<string>;

export function ExtractFragmentsFromMarkers():Promise<Array<string>>;

export function GetAllFragments():Promise<Array<Backend.Data_fragment>>;

export function GetAvailableTools():Promise<Array<Backend.Tool_info>>;

export function GetConcatenatedFragmentID():Promise<string>;

export function GetFragment(arg1:string):Promise<Backend.Data_fragment>;

export function GetFragmentCount():Promise<number>;

export function GetSourceFragments():Promise<Array<Backend.Data_fragment>>;

export function GetSourceFragmentsMetadata():Promise<Array<Backend.Fragment_metadata>>;

export function HasConcatenatedFragment():Promise<boolean>;
