// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllFragments() {
  return window['go']['Backend']['Tool_manager']['ClearAllFragments']();
}

export function ConcatenateAllFragments() {
  return window['go']['Backend']['Tool_manager']['ConcatenateAllFragments']();
}

export function DeleteConcatenatedFragment() {
  return window['go']['Backend']['Tool_manager']['DeleteConcatenatedFragment']();
}

export function DeleteFragment(arg1) {
  return window['go']['Backend']['Tool_manager']['DeleteFragment'](arg1);
}

export function ExecuteTool(arg1, arg2, arg3) {
  return window['go']['Backend']['Tool_manager']['ExecuteTool'](arg1, arg2, arg3);
}

export function ExtractDataFragment(arg1, arg2) {
  return window['go']['Backend']['Tool_manager']['ExtractDataFragment'](arg1, arg2);
}

export function ExtractFragmentsFromMarkers() {
  return window['go']['Backend']['Tool_manager']['ExtractFragmentsFromMarkers']();
}

export function GetAllFragments() {
  return window['go']['Backend']['Tool_manager']['GetAllFragments']();
}

export function GetAvailableTools() {
  return window['go']['Backend']['Tool_manager']['GetAvailableTools']();
}

export function GetConcatenatedFragmentID() {
  return window['go']['Backend']['Tool_manager']['GetConcatenatedFragmentID']();
}

export function GetFragment(arg1) {
  return window['go']['Backend']['Tool_manager']['GetFragment'](arg1);
}

export function GetFragmentCount() {
  return window['go']['Backend']['Tool_manager']['GetFragmentCount']();
}

export function GetSourceFragments() {
  return window['go']['Backend']['Tool_manager']['GetSourceFragments']();
}

export function GetSourceFragmentsMetadata() {
  return window['go']['Backend']['Tool_manager']['GetSourceFragmentsMetadata']();
}

export function HasConcatenatedFragment() {
  return window['go']['Backend']['Tool_manager']['HasConcatenatedFragment']();
}
