// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTag(arg1) {
  return window['go']['logFileParser']['Telemetry_file']['AddTag'](arg1);
}

export function Baby_serialize() {
  return window['go']['logFileParser']['Telemetry_file']['Baby_serialize']();
}

export function Load_telemetry_file(arg1) {
  return window['go']['logFileParser']['Telemetry_file']['Load_telemetry_file'](arg1);
}

export function RemoveTag(arg1) {
  return window['go']['logFileParser']['Telemetry_file']['RemoveTag'](arg1);
}

export function SetName(arg1) {
  return window['go']['logFileParser']['Telemetry_file']['SetName'](arg1);
}
