// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTag(arg1:string):Promise<void>;

export function Baby_serialize():Promise<string>;

export function Load_telemetry_file(arg1:string):Promise<void>;

export function RemoveTag(arg1:string):Promise<void>;

export function SetName(arg1:string):Promise<void>;
