// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NotifyGraphRefresh() {
  return window['go']['main']['App']['NotifyGraphRefresh']();
}

export function OpenChannelManagerWindow() {
  return window['go']['main']['App']['OpenChannelManagerWindow']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}
